/**
 * GENERATED by scripts/derive-wide-view.mjs — DO NOT EDIT BY HAND.
 *
 * A census of who is in each plate, taken from the plates. Regenerate with
 *   node scripts/derive-wide-view.mjs
 * then re-run the tests, re-render the contact sheet, look at it, and approve:
 *   npx vitest run src/test/the-wide-view.test.ts
 *   node scripts/derive-wide-view.mjs --sheet
 *   node scripts/derive-wide-view.mjs --approve
 *
 * Every sentence the exercise speaks is generated from these four fields. There
 * is no prose here to drift away from the picture, and no coordinate here that
 * a hand can move without turning the suite red.
 */

/** What a body is doing, as far as pixels can settle it. Closed on purpose. */
export type Pose = 'stand' | 'sit-floor' | 'sit-seat' | 'kneel' | 'crouch' | 'climb' | 'lie' | 'part-hidden';

/** Which way the head points, in the plane of the picture. */
export type Facing = 'left' | 'right' | 'towards' | 'away';

export interface Person {
  /** Position in the census, stable across regenerations. */
  readonly id: string;
  /** [x0, y0, x1, y1] as fractions of the plate, tight to the whole visible body. */
  readonly box: readonly [number, number, number, number];
  readonly pose: Pose;
  readonly facing: Facing;
  readonly adult: boolean;
}

export interface Room {
  readonly id: string;
  /** games/sel/<plate>.png */
  readonly plate: string;
  /** The plate as it was when the census was taken. */
  readonly plateSha: string;
  /** Straight out of the PNG header, so the crop maths cannot assume an aspect. */
  readonly plateWidth: number;
  readonly plateHeight: number;
  /** A caption for the room. The one authored string, and it names no person. */
  readonly place: string;
  /** However many people are in the picture. There is no floor and no quota. */
  readonly people: readonly Person[];
}

export const SEAL = {
  plates: {
    carpet: '39388a6f0a4d24ecebdfc364a2e23592e58e779d3174cd685860ee40aa871a62',
    recess: '941633923d85ed80e844387bb5ce0f3663c984f10f4c1af79977996d2b8bb3c1',
    party: '6f3ae2207fefae0aa0e41215614799abef5a242520e8a057a70345930d1603aa',
    playdate: '3079194d74095e42f6d02aa4b84ac4050b002ba2eb448af5d8d3a9bb98418c35',
    dinner: '40a21a5bd05afa9c7b333aaa346d0d052139f7d15fbecd143756085c84315cce',
    museum: '9bc55850c7f05c56d6c861f0e910c7da496422b6af1f99a767df97e935a5f9dd',
  } as Record<string, string>,
  /** sha256 of every line below the sentinel. */
  body: '52c78bfb5381177aace67f04f34088ba57b63f10b60b32a359b8073b3a2af793',
  /** sha256 of artifacts/wide-view.json at the moment a person looked at the sheet. */
  looked: '14202d5cf1dfa5ce815d284566018080e062b385158824198b6af4c839535862',
} as const;

// ---- sealed body: every line below is hashed into SEAL.body ----

export const ROOMS: readonly Room[] = [
  {
    id: 'carpet',
    plate: 'the-wide-view-carpet',
    plateSha: '39388a6f0a4d24ecebdfc364a2e23592e58e779d3174cd685860ee40aa871a62',
    plateWidth: 900,
    plateHeight: 700,
    place: 'The classroom carpet, story time',
    people: [
      { id: 'p01', box: [0.207, 0.178, 0.277, 0.478], pose: 'stand', facing: 'right', adult: true },
      { id: 'p02', box: [0.306, 0.178, 0.377, 0.370], pose: 'stand', facing: 'away', adult: true },
      { id: 'p03', box: [0.278, 0.360, 0.336, 0.606], pose: 'stand', facing: 'right', adult: false },
      { id: 'p04', box: [0.345, 0.322, 0.422, 0.492], pose: 'sit-floor', facing: 'towards', adult: false },
      { id: 'p05', box: [0.492, 0.222, 0.578, 0.510], pose: 'sit-seat', facing: 'towards', adult: true },
      { id: 'p06', box: [0.743, 0.240, 0.801, 0.390], pose: 'stand', facing: 'towards', adult: false },
      { id: 'p07', box: [0.616, 0.374, 0.708, 0.558], pose: 'kneel', facing: 'right', adult: false },
      { id: 'p08', box: [0.728, 0.397, 0.789, 0.569], pose: 'kneel', facing: 'left', adult: false },
      { id: 'p09', box: [0.802, 0.385, 0.858, 0.665], pose: 'stand', facing: 'left', adult: false },
      { id: 'p10', box: [0.722, 0.542, 0.833, 0.727], pose: 'sit-floor', facing: 'left', adult: false },
      { id: 'p11', box: [0.166, 0.509, 0.286, 0.730], pose: 'sit-floor', facing: 'right', adult: false },
      { id: 'p12', box: [0.344, 0.616, 0.467, 0.823], pose: 'sit-floor', facing: 'away', adult: false },
      { id: 'p13', box: [0.558, 0.656, 0.689, 0.823], pose: 'sit-floor', facing: 'right', adult: false },
    ],
  },
  {
    id: 'recess',
    plate: 'the-wide-view-recess',
    plateSha: '941633923d85ed80e844387bb5ce0f3663c984f10f4c1af79977996d2b8bb3c1',
    plateWidth: 900,
    plateHeight: 700,
    place: 'The playground at recess',
    people: [
      { id: 'p01', box: [0.085, 0.213, 0.146, 0.410], pose: 'stand', facing: 'right', adult: false },
      { id: 'p02', box: [0.167, 0.183, 0.229, 0.338], pose: 'climb', facing: 'right', adult: false },
      { id: 'p03', box: [0.245, 0.113, 0.315, 0.337], pose: 'climb', facing: 'right', adult: false },
      { id: 'p04', box: [0.328, 0.203, 0.385, 0.397], pose: 'stand', facing: 'left', adult: false },
      { id: 'p05', box: [0.525, 0.233, 0.585, 0.467], pose: 'stand', facing: 'right', adult: false },
      { id: 'p06', box: [0.605, 0.243, 0.665, 0.470], pose: 'stand', facing: 'left', adult: false },
      { id: 'p07', box: [0.755, 0.183, 0.805, 0.377], pose: 'stand', facing: 'towards', adult: false },
      { id: 'p08', box: [0.875, 0.223, 0.925, 0.427], pose: 'stand', facing: 'towards', adult: false },
      { id: 'p09', box: [0.125, 0.453, 0.192, 0.667], pose: 'stand', facing: 'right', adult: false },
      { id: 'p10', box: [0.255, 0.453, 0.315, 0.667], pose: 'stand', facing: 'left', adult: false },
      { id: 'p11', box: [0.405, 0.393, 0.472, 0.605], pose: 'stand', facing: 'left', adult: false },
      { id: 'p12', box: [0.685, 0.513, 0.755, 0.640], pose: 'sit-floor', facing: 'towards', adult: false },
      { id: 'p13', box: [0.828, 0.503, 0.935, 0.907], pose: 'stand', facing: 'left', adult: true },
      { id: 'p14', box: [0.065, 0.713, 0.135, 0.937], pose: 'stand', facing: 'right', adult: false },
      { id: 'p15', box: [0.184, 0.733, 0.255, 0.947], pose: 'stand', facing: 'right', adult: false },
      { id: 'p16', box: [0.391, 0.657, 0.525, 0.907], pose: 'stand', facing: 'right', adult: false },
    ],
  },
  {
    id: 'party',
    plate: 'the-wide-view-party',
    plateSha: '6f3ae2207fefae0aa0e41215614799abef5a242520e8a057a70345930d1603aa',
    plateWidth: 900,
    plateHeight: 700,
    place: 'A birthday party',
    people: [
      { id: 'p01', box: [0.155, 0.303, 0.224, 0.615], pose: 'stand', facing: 'right', adult: false },
      { id: 'p02', box: [0.104, 0.558, 0.212, 0.828], pose: 'stand', facing: 'left', adult: false },
      { id: 'p03', box: [0.317, 0.387, 0.412, 0.548], pose: 'part-hidden', facing: 'right', adult: false },
      { id: 'p04', box: [0.408, 0.385, 0.469, 0.525], pose: 'part-hidden', facing: 'right', adult: false },
      { id: 'p05', box: [0.526, 0.207, 0.598, 0.535], pose: 'stand', facing: 'right', adult: true },
      { id: 'p06', box: [0.598, 0.205, 0.655, 0.535], pose: 'stand', facing: 'right', adult: true },
      { id: 'p07', box: [0.655, 0.211, 0.766, 0.425], pose: 'stand', facing: 'left', adult: true },
      { id: 'p08', box: [0.649, 0.375, 0.714, 0.531], pose: 'part-hidden', facing: 'towards', adult: false },
      { id: 'p09', box: [0.712, 0.402, 0.777, 0.548], pose: 'part-hidden', facing: 'left', adult: false },
      { id: 'p10', box: [0.304, 0.545, 0.462, 0.771], pose: 'kneel', facing: 'right', adult: false },
      { id: 'p11', box: [0.453, 0.525, 0.545, 0.798], pose: 'sit-floor', facing: 'left', adult: false },
      { id: 'p12', box: [0.595, 0.605, 0.687, 0.827], pose: 'sit-floor', facing: 'right', adult: false },
      { id: 'p13', box: [0.710, 0.555, 0.803, 0.798], pose: 'sit-floor', facing: 'left', adult: false },
    ],
  },
  {
    id: 'playdate',
    plate: 'the-wide-view-playdate',
    plateSha: '3079194d74095e42f6d02aa4b84ac4050b002ba2eb448af5d8d3a9bb98418c35',
    plateWidth: 900,
    plateHeight: 700,
    place: 'A play date at their house',
    people: [
      { id: 'p01', box: [0.380, 0.249, 0.487, 0.538], pose: 'sit-seat', facing: 'towards', adult: true },
      { id: 'p02', box: [0.285, 0.329, 0.367, 0.534], pose: 'sit-seat', facing: 'towards', adult: false },
      { id: 'p03', box: [0.666, 0.191, 0.737, 0.443], pose: 'stand', facing: 'away', adult: true },
      { id: 'p04', box: [0.828, 0.313, 0.937, 0.502], pose: 'sit-seat', facing: 'left', adult: true },
      { id: 'p05', box: [0.518, 0.344, 0.600, 0.668], pose: 'stand', facing: 'right', adult: false },
      { id: 'p06', box: [0.601, 0.354, 0.686, 0.668], pose: 'stand', facing: 'left', adult: false },
      { id: 'p07', box: [0.737, 0.329, 0.794, 0.584], pose: 'stand', facing: 'towards', adult: false },
      { id: 'p08', box: [0.122, 0.529, 0.231, 0.761], pose: 'sit-floor', facing: 'right', adult: false },
      { id: 'p09', box: [0.355, 0.551, 0.447, 0.736], pose: 'sit-floor', facing: 'left', adult: false },
      { id: 'p10', box: [0.739, 0.559, 0.887, 0.802], pose: 'part-hidden', facing: 'left', adult: false },
    ],
  },
  {
    id: 'dinner',
    plate: 'the-wide-view-dinner',
    plateSha: '40a21a5bd05afa9c7b333aaa346d0d052139f7d15fbecd143756085c84315cce',
    plateWidth: 900,
    plateHeight: 700,
    place: 'The dinner table',
    people: [
      { id: 'p01', box: [0.064, 0.353, 0.128, 0.623], pose: 'stand', facing: 'towards', adult: false },
      { id: 'p02', box: [0.153, 0.255, 0.228, 0.619], pose: 'stand', facing: 'towards', adult: false },
      { id: 'p03', box: [0.270, 0.201, 0.342, 0.425], pose: 'stand', facing: 'towards', adult: true },
      { id: 'p04', box: [0.402, 0.164, 0.474, 0.375], pose: 'stand', facing: 'towards', adult: true },
      { id: 'p05', box: [0.262, 0.319, 0.422, 0.810], pose: 'sit-seat', facing: 'right', adult: true },
      { id: 'p06', box: [0.391, 0.307, 0.505, 0.535], pose: 'sit-seat', facing: 'right', adult: true },
      { id: 'p07', box: [0.493, 0.262, 0.552, 0.440], pose: 'sit-seat', facing: 'towards', adult: true },
      { id: 'p08', box: [0.566, 0.217, 0.638, 0.418], pose: 'sit-seat', facing: 'towards', adult: true },
      { id: 'p09', box: [0.696, 0.264, 0.760, 0.369], pose: 'sit-seat', facing: 'towards', adult: false },
      { id: 'p10', box: [0.781, 0.231, 0.849, 0.376], pose: 'part-hidden', facing: 'towards', adult: true },
      { id: 'p11', box: [0.815, 0.267, 0.934, 0.745], pose: 'sit-seat', facing: 'left', adult: true },
      { id: 'p12', box: [0.729, 0.364, 0.834, 0.530], pose: 'sit-seat', facing: 'left', adult: false },
      { id: 'p13', box: [0.164, 0.548, 0.261, 0.760], pose: 'sit-seat', facing: 'towards', adult: false },
      { id: 'p14', box: [0.521, 0.506, 0.640, 0.860], pose: 'sit-seat', facing: 'right', adult: false },
      { id: 'p15', box: [0.696, 0.482, 0.807, 0.775], pose: 'sit-seat', facing: 'left', adult: false },
    ],
  },
  {
    id: 'museum',
    plate: 'the-wide-view-museum',
    plateSha: '9bc55850c7f05c56d6c861f0e910c7da496422b6af1f99a767df97e935a5f9dd',
    plateWidth: 900,
    plateHeight: 700,
    place: 'The museum hall',
    people: [
      { id: 'p01', box: [0.056, 0.563, 0.128, 0.826], pose: 'stand', facing: 'right', adult: false },
      { id: 'p02', box: [0.134, 0.652, 0.212, 0.836], pose: 'stand', facing: 'right', adult: false },
      { id: 'p03', box: [0.255, 0.474, 0.364, 0.736], pose: 'sit-seat', facing: 'right', adult: true },
      { id: 'p04', box: [0.422, 0.481, 0.487, 0.737], pose: 'stand', facing: 'right', adult: false },
      { id: 'p05', box: [0.513, 0.417, 0.569, 0.651], pose: 'stand', facing: 'right', adult: false },
      { id: 'p06', box: [0.574, 0.387, 0.630, 0.641], pose: 'stand', facing: 'left', adult: true },
      { id: 'p07', box: [0.647, 0.390, 0.699, 0.644], pose: 'stand', facing: 'left', adult: true },
      { id: 'p08', box: [0.501, 0.656, 0.613, 0.798], pose: 'crouch', facing: 'right', adult: false },
      { id: 'p09', box: [0.602, 0.649, 0.683, 0.798], pose: 'crouch', facing: 'left', adult: false },
      { id: 'p10', box: [0.712, 0.508, 0.803, 0.656], pose: 'crouch', facing: 'right', adult: false },
      { id: 'p11', box: [0.812, 0.486, 0.920, 0.656], pose: 'kneel', facing: 'right', adult: false },
      { id: 'p12', box: [0.653, 0.644, 0.953, 0.956], pose: 'lie', facing: 'left', adult: true },
    ],
  },
] as const;

export const TOTAL_PEOPLE = ROOMS.reduce((n, r) => n + r.people.length, 0);
